# Programmed by Keyhan Babaee Under Prof. Steven Rogak supervision, https://github.com/KeyhanB
# Using Fortran Code from: C. Liu, X. Xu, Y. Yin, M. Schnaiter, Y. L. Yung, 2018: Black carbon aggregate: A database for optical properties
Version = 0.3
# Oct 2019
import ConfigReaderModule as CP
from ConfigReaderModule import logging
import RDG_TMatrixCalculator as RDGTMV2

if __name__ == "__main__":
    CP.ReadLogConfig()
    logging.info("App Started.")
    DB_Info = CP.ReadConfigToDict(sectionName="DatabaseInfo")
    FF_Info = CP.ReadConfigToDict(sectionName="FilesFoldersInfo")
    AGG_Info = CP.ReadConfigToDict(sectionName="AggregateDetails", convertParseTo='float', hasComment=True)
    logging.info("config retrieved.")
    ##############################################

    conArr = [
        {'AGG_EFF_RHO_100NM_CENTER': 502, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.56},
        {'AGG_EFF_RHO_100NM_CENTER': 502, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.56},
        {'AGG_EFF_RHO_100NM_CENTER': 502, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.56},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 450, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 550, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.2},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.5},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.4, 'AGG_EFF_DM_CENTER': 2.8},
        {'AGG_EFF_RHO_100NM_CENTER': 650, 'AGG_POLYDISPERSITY_SIGMA_EACH_MOBILITY_CENTER': 1.8, 'AGG_EFF_DM_CENTER': 2.8},
    ]

    for con in conArr:
        for key in con:
            AGG_Info[key] = con[key]
        RTC02 = RDGTMV2.KeyhanV2(AGG_Info)
        RTC02.KeyhanV2Calc(DB_Info)
    ################################################################################################################
    logging.info("App finished.")
